apiVersion: v1
kind: Service
metadata:
  name: {{ include "backrest.fullname" . }}
  labels:
    {{- include "backrest.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backrest.selectorLabels" . | nindent 4 }}